version: '3.7'

services:
    application:
      working_dir: /application
      build: 
        context: ./application
        dockerfile: ../sourcefiles/node/Dockerfile
      container_name: ${PROJECT_NAME}-backend
      restart: unless-stopped
      ports: 
        - 3000:3000
      volumes: 
        - ./application:/application
      networks: 
        selina:
    webserver: 
      image: nginx:alpine
      container_name: ${PROJECT_NAME}-webserver
      restart: unless-stopped
      working_dir: /var/www
      volumes:
        - ./application:/var/www
        - ./sourcefiles/nginx/:/etc/nginx/conf.d
      ports:
        - "80:80"
        - "4443:443"
      networks:
        selina:
    db:
      image: postgres:14-alpine
      container_name: ${PROJECT_NAME}-postgres
      restart: unless-stopped
      volumes:
        - ./sourcefiles/postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_DATABASE}
      ports:
        - "5432:5432"
      networks:
        selina:
networks:
    selina:
      driver: bridge